---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-shop
  labels:
    app: rental-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rental-shop
  template:
    metadata:
      labels:
        app: rental-shop
    spec:
      containers:
        - name: rental-shop
          image: archepro84/rental-shop:v0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10