---
apiVersion: v1
kind: Service
metadata:
  name: rental-shop
  labels:
    app: rental-shop
spec:
  ports:
    - protocol: TCP
      port: 8085 # Host Port
      targetPort: 8080 # Container Port
  type: LoadBalancer # 해당 Service의 Public IP 및 Port 할당
  selector:
    app: rental-shop