---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock
  labels:
    app: stock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
        - name: stock
          image: archepro84/stock:v0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10